Feature1 2
yulyana1994/toys pull request #1
Opened 2022-08-27 07:39 UTC by yulyana1994

сделаны карточки

2022-08-28 06:54 UTC, ArturZhitkovich requested changes
Куда ты спешишь ?

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/package.json
> +    "react": "^18.2.0",
ТОчно 18 версию хочешь ?

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/Categories/categories.module.css
> +    grid-area: categories;
А что это такое ?

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/Header/Korzina/korzina.jsx
> +    <div>
А зачем ты везде обаричиваешь в div?

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/Header/Korzina/korzina.module.css
> +color: #6b5770;
Отступы

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/Header/Korzina/korzina.module.css
> +color: #6b5770;
Во всем файл

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/Header/header.jsx
> +        <div className={s.enter}>Вход/Регистрация</div>
Класс вообще пушка, хорошо что не s.vhod

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/MainPage/mainPage.jsx
> +  return (
Пустую строку пожалуйста

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/MainPage/mainPage.jsx
> +  const [toys, setToys] = useState(api.toys.fetchAll());
А почему сразу не сделать промисом

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/MainPage/mainPage.jsx
> +  const [toys, setToys] = useState(api.toys.fetchAll());
И я не думаю, что список продуктов, надо называть toys и что этот список должен быть в этом компоненте

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/MainPage/mainPage.jsx
> +  const [toys, setToys] = useState(api.toys.fetchAll());
Это перенеси в компонент с продуктами

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/MainPage/mainPage.module.css
> +.appWrapper{
Что ха неминг такой ?

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/Sort/sort.module.css
> +    background-color: salmon;
интересный цвет ))))

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/ToysCard/Card/card.jsx
> +const Card = ({ name, src, artikul, price }) => {
Ну это же не полноценная карточка товара

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/ToysCard/Card/card.jsx
> +const Card = ({ name, src, artikul, price }) => {
Почему нет ни логики, не стейта

2022-08-28 06:54 UTC, ArturZhitkovich commented on toys-store/src/components/ToysCard/Card/card.jsx
> +const Card = ({ name, src, artikul, price }) => {
Зачем ты делаешь тупо верстку, куда ты спешишь ?

2022-08-28 06:55 UTC, ArturZhitkovich commented on toys-store/src/components/Header/Korzina/korzina.jsx
> +    <div>
нейминг просто вау

2022-08-28 07:18 UTC, yulyana1994 commented on toys-store/src/components/Categories/categories.module.css
> +    grid-area: categories;
гриды

2022-08-28 07:18 UTC, yulyana1994 commented on toys-store/package.json
> +    "react": "^18.2.0",
можно просто тут перебить на 17, или нет?

2022-08-28 07:58 UTC, yulyana1994 commented on toys-store/src/components/ToysCard/Card/card.jsx
> +const Card = ({ name, src, artikul, price }) => {
потому что я не знаю что должно быть, Артур!!!! откуда мне знать если я делаю это впервые!!!! может это ты должен расписать что должно быть? задача от тебя : Использую мокковые(тестовые) данные реализовать карточку товара. я ее реализовала, если не так как ты хотел, то надо писать что там должно быть, я же не знаю как оно должно быть!!!

2022-08-31 09:26 UTC, ArturZhitkovich reviewed
Все деректирии с маленькой буквы

2022-08-31 09:26 UTC, ArturZhitkovich commented on toys-store/package.json
> +    "react": "^18.2.0",
Да

2022-08-31 09:34 UTC, ArturZhitkovich reviewed
Есть замечания

2022-08-31 09:34 UTC, ArturZhitkovich commented on toys-store/src/App.js
> +import Cart from "./pages/Cart/cart";
pages/cart/CartPage

в папке pages - делаешь папку cart
в папке cart  -> CartPage

2022-08-31 09:34 UTC, ArturZhitkovich commented on toys-store/src/App.js
> +import Login from "./pages/Login/login";
и так везде

2022-08-31 09:34 UTC, ArturZhitkovich commented on toys-store/src/components/Info/info.jsx
> +          <a href="https://www.instagram.com/yulianna.shulzhenko/">
target="_blank" - добавь атрибут

2022-08-31 09:34 UTC, ArturZhitkovich commented on toys-store/src/components/ToysCard/idToysCard.jsx
> +const IdToysCard = () => {
Это что такое?

2022-08-31 09:34 UTC, ArturZhitkovich commented on toys-store/src/components/ToysCard/toysCard.jsx
> +  useEffect(() => {
пустую строуку

2022-08-31 09:34 UTC, ArturZhitkovich commented on toys-store/src/components/ToysCard/toysCard.jsx
> +  let toysCard = toys.map((el) => (
const renderToysCard

Ну проще сраузу в рендере

2022-08-31 09:34 UTC, ArturZhitkovich commented on toys-store/src/components/ToysCard/toysCard.jsx
> +    <Card
Кажется, проще передавать объект, а не каждый ключ

2022-08-31 09:59 UTC, merged

2022-08-31 09:59 UTC, yulyana1994 commented
Feature1 2